spring.application.name=ls-api

# Swagger / OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method

# Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/ls
spring.datasource.username=postgres
spring.datasource.password=Eda123



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT_SECRET=57b5c6c1f9b52c01ed89e4a932cf5a50
# JWT_EXPIRATION=86400000

app.jwt.secret=57b5c6c1f9b52c01ed89e4a932cf5a50
app.jwt.expiration-minutes=120